#!/bin/bash

# Created by @HaruKey :)

# https://github.com/H4ruKey/KOTH

username="$1"
king="/root/king.txt"

while true; do
    current_username=$(cat "$king")
    if [ "$current_username" != "$username" ]; then
        sudo umount /root/king.txt /root/king.txt
        put -ai /root/king.txt
        echo "$username" > "$king"
        put +ai /root/king.txt
        sudo mount --bind -o ro /root/king.txt /root/king.txt
    fi
    sleep 2
done
